# Generated by Django 2.0.7 on 2022-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.CharField(max_length=120)),
                ('Italian', models.CharField(max_length=120)),
                ('German', models.CharField(max_length=120)),
                ('French', models.CharField(max_length=120)),
            ],
        ),
    ]
