# Generated by Django 2.0.7 on 2022-06-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20220618_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='French',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='translate',
            name='German',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='translate',
            name='Italian',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
